Swapped order of sentences
carpentries-incubator/python-intermediate-development pull request #225
Opened 2023-07-27 13:38 UTC by anenadic

2023-08-02 17:31 UTC, bielsnohr requested changes
LGTM. Just a few minor sembr changes.

2023-08-02 17:31 UTC, bielsnohr commented on README.md
> +they are grouped and work in teams, as they would when collaborating on a team software project development.
Sembr
```suggestion
The lesson is suitable for both instructor-led teaching or guided self-learning where instructors provide help 
and answer questions (synchronously or asynchrounously) as learners go through the course on their own. 
Initially, in sections 1-3 
of the lesson, learners are working on a software project and going though exercises individually.
In sections 4 and 5,
they are grouped and work in teams, as they would when collaborating on a team software project development.
```

2023-08-02 17:31 UTC, bielsnohr commented on README.md
> +depending on the pace (we would recommend setting aside 1 day per section to make sure the delivery is not rushed).
Sembr and punctuation changes

```suggestion
The lesson has 5 sections; 
each section can be delivered or worked through in self-learning mode over a half a day to a day, 
depending on the pace.
We would recommend setting aside one day per section to make sure the delivery is not rushed. 
```

2023-08-03 09:36 UTC, anenadic reviewed
Thank you for the comments @bielsnohr - if this is looking OK now do you mind approving the PR please so it can be merged?

2023-08-04 09:34 UTC, bielsnohr approved these changes
Made a few quick changes myself. All good now.

2023-08-04 09:35 UTC, merged