Remove old course content and add new pages
carpentries-incubator/python-intermediate-development pull request #234
Opened 2023-08-09 14:06 UTC by thomaskileyukaea

This is a re-write of section 3, to address the #227. The aim is to focus on refactoring existing code, and demonstrate the principles of OOP, functional etc through examples where they are useful, rather than explicitly teaching them as concepts. The hope is that the result will be quicker and easier to teach. 

The changes rely on a new bit of code in the example project. This can be found here:

https://github.com/thomaskileyukaea/python-intermediate-inflammation/commit/cfb377c55f070551d9bba40d56bc8a371ae01f34

This change lives on a branch, and the subsequent commits are the solutions to the exericses, where the reader will refactor the code. It may therefore be useful to observe the commits on this branch one by one to get the idea: 

https://github.com/thomaskileyukaea/python-intermediate-inflammation/commits/refactor-standard-deviation-across-all-data

# Still to do for structural draft

 - [ ] Add headers for the new pages
 - [ ] Add exercises 
 - [ ] Review the removed questisons / objectives / keypoints to determine if they are still covered, or should be cut
 - [ ] Review the removed content to determine if the important stuff is still covered

# Still to do for first draft

- [ ] Update section 3 intro
- [ ] Line by line read through
- [ ] Solo run to iron out issues
- [ ] Dummy run with another person to get a sense of timing and identify issues

2023-10-18 16:29 UTC, thomaskileyukaea reviewed
- [ ]  There is overlap between questions and objectives for lots of the episodes - would be good to understand the difference and refine this
- [ ] Don't have imports inside the test functions - is not best practise

Things to discuss:
* (how) should we mention DRY
* Should we remove the interfaces bit - seems a bit unnecessary in an untyped lang like python

2023-10-18 17:03 UTC, anenadic commented
> * [ ]   There is overlap between questions and objectives for lots of the episodes - would be good to understand the difference and refine this

Questions are lesson objectives reworded as questions that will be answered as part of the episode but in a language that is more understandable to the audience and without the potentially unfamiliar terminology used in lesson objectives.

2023-10-20 16:24 UTC, thomaskileyukaea commented
> > * [ ]    There is overlap between questions and objectives for lots of the episodes - would be good to understand the difference and refine this
> 
> Questions are lesson objectives reworded as questions that will be answered as part of the episode but in a language that is more understandable to the audience and without the potentially unfamiliar terminology used in lesson objectives.

That's really helpful @anenadic thank you! I won't worry too much about them sounding like they are repeating themselves, but I'll do a pass to ensure the q's are all in simple language.

2023-10-23 17:05 UTC, thomaskileyukaea commented on _episodes/35-refactoring-decoupled-units.md
> +
Decided to instead remove interfaces as an actual thing

2023-11-01 11:12 UTC, bielsnohr requested changes
Please change episode titles to respect title case used for all other episodes in course

2023-11-01 11:12 UTC, bielsnohr commented on _episodes/33-refactoring-functions.md
> +title: "Refactoring functions to do just one thing"
```suggestion
title: "Refactoring Functions to Do Just One Thing"
```

2023-11-01 11:12 UTC, bielsnohr commented on _episodes/34-refactoring-decoupled-units.md
> +title: "Using classes to de-couple code."
```suggestion
title: "Using Classes to De-Couple Code"
```

2023-11-01 11:12 UTC, bielsnohr commented on _episodes/35-refactoring-architecture.md
> +title: "Architecting code to separate responsibilities"
```suggestion
title: "Architecting Code to Separate Responsibilities"
```

2023-11-22 11:45 UTC, bielsnohr approved these changes
Thanks for the minor fixes. All good from my end. Passing on to other maintainers.

2023-12-11 11:24 UTC, douglowe commented on _episodes/30-section3-intro.md
> +- How to create, asses and improve software design.
'assess' rather than 'asses'?

2023-12-11 15:07 UTC, anenadic commented
Merging to a local branch from Thomas's repo for easier review as Thomas's time on this project ended and then will reopen a new PR.

2023-12-12 11:30 UTC, merged

2023-12-12 15:54 UTC, anenadic commented
> * [ ]   There is overlap between questions and objectives for lots of the episodes - would be good to understand the difference and refine this
[snip]

The questions help learners understand what to expect from an episode/lesson as they might not yet understand the learning objectives.