Replacing checkout with switch
carpentries-incubator/python-intermediate-development pull request #264
Opened 2023-11-09 17:20 UTC by anenadic

2023-11-10 10:51 UTC, anenadic commented
Any chance you can have a look at this PR @bielsnohr?

2023-11-12 17:36 UTC, douglowe approved these changes
These changes look sensible to me.

2023-11-13 10:01 UTC, bielsnohr requested changes
Just a few minor corrections before we merge in.

2023-11-13 10:01 UTC, bielsnohr commented on _episodes/14-collaboration-using-git.md
> +    Remote Repository->>+Working Directory: git pull (shortcut for git fetch followed by git checkout / switch / merge)
I will push a separate commit updating the SVG image below.

2023-11-13 11:43 UTC, anenadic commented on _episodes/14-collaboration-using-git.md
> +    Remote Repository->>+Working Directory: git pull (shortcut for git fetch followed by git checkout / switch / merge)
Thank you @bielsnohr

2023-11-13 11:45 UTC, anenadic commented
Thank you for catching those few "checkouts" @bielsnohr - do you think it's ready to be merged?

2023-11-13 18:11 UTC, bielsnohr approved these changes
LGTM!

2023-11-13 18:12 UTC, merged