Move imports outside of test method code
carpentries-incubator/python-intermediate-development pull request #379
Opened 2024-09-12 12:51 UTC by johnnonweiler

Closes #266

2024-09-12 12:54 UTC, bielsnohr approved these changes
Quite a simple change. LGTM.

2024-09-12 13:08 UTC, bielsnohr commented on _episodes/22-scaling-up-unit-testing.md
> +> > from inflammation.models import daily_min
We can make this into a single line
```suggestion
> > from inflammation.models import daily_max, daily_min
```

2024-09-25 12:39 UTC, bielsnohr requested changes
On second inspection, there are still some cases in the content where import statements are within code snippets, namely `21-automatically-testing-software.md`.

@johnnonweiler if you give me permission to add commits [like this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) then I can add the subsequent changes needed.

2024-09-25 12:40 UTC, bielsnohr commented
> On second inspection, there are still some cases in the content where import statements are within code snippets, namely `21-automatically-testing-software.md`.
> 
> @johnnonweiler if you give me permission to add commits [like this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) then I can add the subsequent changes needed.

Ah, I just realised that I can actually make edits to this PR directly, so no need to do the step in the link I sent.

2024-09-26 11:36 UTC, bielsnohr commented
Okay, I think I did a good enough regex search to get all the instances of modules being imported inside of a test function. Because this change expanded beyond what I initially thought it would be, we likely need to verify that all or most of the code snippet changed actually still run properly. I don't have the time for that at the moment, however, we will be running the course again at UKAEA, so we could be the test subjects.

2024-10-03 11:18 UTC, steve-crouch commented
Looks good, we'll just need to verify these changes then. After discussion with Aleks, due to time constraints, retiring this PR for now until the material is transitioned to the new Carpentries format, when we'll recreate it and can work on it from there.

2024-10-21 16:51 UTC, bielsnohr approved these changes
I have found some time to go through most of the code snippet changes and incorporate them into the starting point that https://github.com/carpentries-incubator/python-intermediate-inflammation/pull/18 will implement. Everything works fine, so I am going to approve this.

2024-10-21 16:51 UTC, merged